const dataList = [
  {
    name: "Fentanyl",
    tradeName: "Sublimaze",
    action: "Potent narcotic analgesic",
    indications: ["Significant pain."],
    contraindications: ["Known sensitivity to fentanyl."],
    sideEffects: [
      "Rapid injection can cause respiratory arrest or chest wall rigidity.",
      "Administer over 30-60 seconds.",
      "Central nervous system depressant, which can cause respiratory depression, peripheral vasodilation, decreased cardiac output and pupillary constriction.",
      "Avoid using if morphine has been given. If morphine given previously, wait at least 5-10 minutes before giving fentanyl and then give cautiously in small amounts.",
      "Do not use if systolic BP < 90 mm Hg or SpO2 < 90%.",
      "Use with caution (smaller or less frequent doses) in the elderly. Naloxone (Narcan) will reverse the effects of fentanyl on respiration.",
    ],
    routes: [
      "Up to 200mcg IV or IO (usual initial dose 0.5-1 mcg/kg IV or IO) over 30-60 seconds OR 1-2 mcg/kg IN, then repeat every 3-5 minutes as needed for severe pain. Maximum total dose the lesser of 4 mcg/kg or 500mcg in non-intubated patient ",
    ],
    ivInfusion: ["0.5-4mcg/kg/hour IV infusion. Titrate to desired effect. "],
  },
  {
    name: "Ketamine",
    tradeName: "Ketalar",
    action:
      "Rapid-acting dissociative anesthetic agent and analgesic with minimal depression on respiration or blood pressure.  May cause some hypertension and tachycardia. IV onset in 2-5 minutes; effects last 15-20 minutes.",
    indications: [
      "Severe agitation unlikely to respond to alternate sedatives.",
      "Use with great caution in geriatric patients.",
      "Sedation for rapid sequence intubation (RSI)",
      "Severe pain from trauma or burns as an adjunct to opioids.",
      "Severe atraumatic pain in a patient using chronic opioids.",
      "Severe pain in opioid-allergic patient.",
      "Sedation in the high-acuity burn or trauma patient with severe pain AND requiring prolonged extrication.",
      "Post-intubation sedation",
    ],
    contraindications: [
      "Known sensitivity to ketamine.",
      "Pregnancy.",
      "Significant coronary artery disease or",
      "Stroke or acute myocardial infarction in process",
      "Severe hypertension.",
      "Glaucoma",
      "Schizophrenia",
      "Infants less than 3 months of age",
    ],
    sideEffects: [
      "May cause laryngospasm, which may often be controlled with BVM ventilation and time. May require advanced airway management.",
      "May case hypersalivation, which can usually be controlled with suction.",
      "Patient may exhibit “emergence reaction” as medication wears off manifested as “nightmares” and “frightening dreams”.  Can usually be controlled with calming, and may require benzodiazepine administration.",
      "May cause nausea and vomiting; consider premedication with ondansetron.",
      "Caution in elderly patients",
    ],
    routes: [
      "Sedation for RSI, agitated delirium, post-intubation sedation and trauma extrication: 2 mg/kg IV/IO (maximum 300mg) over 1 minute or 4mg/kg IM (maximum 500mg), repeat 1 mg/kg IV or 2 mg/kg IM every 10-15 minutes as needed ",
      "Pain management: 0.15 mg/kg IV/IO (maximum 25mg) over 1 minute or 0.5 mg/kg IM (maximum 50mg), repeat every 5-10 minutes as needed.",
      "Post-intubation sedation: 1– 4 mg/kg/hr infusion ",
      "Suggested infusion by weight:",
      "Under 60 kg: 250mg ketamine in 250mL NS = 1 mg/mL infusion",
      "60-120 kg: 500mg ketamine in 250mL NS = 2 mg/mL infusion",
      "Over 120kg: 1000mg ketamine in 250mL NS = 4mg/mL infusion",
    ],
    ivInfusion: ["NA"],
  },
  {
    name: "LABETALOL",
    tradeName: "NA",
    action: "Intravenous adrenergic alpha and beta blocker",
    indications: [
      "Strict blood pressure management in patients with diagnoses such as:",
      "Malignant Hypertension",
      "Pregnancy Induced Hypertension ",
      "Aortic Aneurysm",
      "Intracranial hemorrhage",
      "Ischemic stroke",
      "Traumatic brain injury",
    ],
    contraindications: [
      "Known sensitivity to labetalol",
      "Hypotension",
      "Cardiogenic or Hypovolemic Shock",
      "Bradycardia or Heart block",
      "Congestive Heart Failure",
    ],
    sideEffects: ["Use with caution in asthmatics."],
    routes: ["20 mg q 10 min slow IV push over 2 minutes, maximum 300mg "],
    ivInfusion: ["NA"],
  },
  {
    name: "MIDAZOLAM",
    tradeName: "Versed",
    action:
      "A short acting benzodiazepine, causing central nervous system depression, respiratory depression, skeletal muscle relaxation and amnesia.",
    indications: [
      "Seizures",
      "Sedation for painful procedures (such as trancutaneous pacing or cardioversion), amputations, severe muscle spasms, or combative patients.",
      "Post RSI sedation.",
    ],
    contraindications: ["Known sensitivity to midazolam."],
    sideEffects: [
      "Administer intravenously in a large bore, free flowing IV.",
      "Respiratory depression, hypotension or sedation are common, particularly in the elderly, in those with chronic disease or in the presence of other sedating agents: alcohol, barbiturates, benzodiazepines or opiates.  Use lower doses.",
      "Paradoxical excitement or agitation may occur.",
    ],
    routes: [
      "Adult: ",
      "1-5 mg IV or IO over 30-60 seconds.  May be given intranasal (IN) if IV or IO unavailable.",
      "5 mg IM for status epilepticus or chemical restraint if IN, IV or IO not available.",
      "May repeat to a maximum total dose of 20 mg.",
      "Pediatric seizures (status epilepticus):",
      "0.2 mg/kg buccal, IN or IM (maximum single dose 5 mg) or",
      "0.1 mg/kg for seizures IV or IO over 30-60 seconds for ongoing seizures or prolonged transport time (maximum single dose 5 mg).",
      "May repeat once.",
      "Pediatric sedation:",
      "0.1 mg/kg for sedation IV or IO over 30-60 seconds (maximum 2.5 mg).",
      "May repeat once.",
      "Post-intubation sedation: ",
      "0.02 – 0.1 mg/kg/hr IV (usual adult dose 2-10 mg/hr)",
      "Suggested infusion: 10mg in 250mL NS = 1 mg/25mL infusion",
    ],
    ivInfusion: ["NA"],
  },
  {
    name: "METOPROLOL",
    tradeName: "NA",
    action: "Intravenous adrenergic beta blocker",
    indications: ["Rate control in narrow-complex tachycardias"],
    contraindications: [
      "Hypotension",
      "Heart block",
      "Bradycardia",
      "Cardiogenic Shock",
      "Congestive Heart Failure",
    ],
    sideEffects: ["Use with caution in patients with asthma."],
    routes: ["5 mg slow IV push q 5 min x 3, maximum of 15 mg"],
    ivInfusion: ["NA"],
  },
  {
    name: "NICARDIPINE",
    tradeName: "Cardene",
    action: "Dihydropyridine calcium channel blocker",
    indications: [
      "Strict blood pressure management in patients with diagnoses such as Intracranial Hemorrhage, Traumatic Brain Injury, and Stroke.",
      "Parameters unless otherwise specified by sending physician:",
      "Acute ischemic stroke:",
      "Thrombectomy: < 180/105, not below 140 systolic",
      "Non-thrombectomy: < 220/120, not below 180/100",
      "Intracranial hemorrhage: <160/90 (target CPP 61-80)",
      "Traumatic brain injury: Goal MAP 80, range 65-100",
    ],
    contraindications: [
      "Known sensitivity to nicardipine",
      "Advanced aortic stenosis",
    ],
    sideEffects: [
      "Incompatible with sodium bicarbonate and Lactated Ringer’s solutions.",
      "Use cautiously in patients with renal, hepatic, or congestive heart failure.  Heart failure can be exacerbated in CHF patients using beta blockers.",
    ],
    routes: [
      "Continuous IV Infusion at 5-15 mg/hr ",
      "Initiate infusion at 5 mg/hr. Titrate infusion by 2.5 mg/hr every 15 minutes to a maximum of 15 mg/hr to achieve desired blood pressure.",
      "*Can be titrated every 5 minutes if needed for rapid blood pressure reduction",
    ],
    ivInfusion: ["NA"],
  },
  {
    name: "PROPOFOL",
    tradeName: "Diprivan",
    action:
      "Sedation by global CNS depression, presumably a GABA-A receptor agonist. ",
    indications: [
      "Maintenance of sedation in intubated and mechanically ventilated patients. ",
      "May initiate if unable to sedate with analgesic, benzodiazepine infusions, or if indicated to maintain appropriate ICP’s. (Physician order from sending preferred) ",
      "Seizures (status epilepticus) not controlled with benzodiazepine administration and with a secure airway.  ",
      "Physician order required for pediatric administration ",
    ],
    contraindications: [
      "Known sensitivity to Propofol",
      "Allergy to soybean oil",
      "Allergy to soy lecithin",
      "Allergy to glycerol",
      "Allergy to egg protein",
      "Use in non-intubated patients",
    ],
    sideEffects: [
      "Will cause decrease in CNS activity, respiratory depression, and hypotension. ",
      "When used in high doses and extended amount of time can cause propofol Infusion Syndrome (lactic acidosis, cardiac dysfunction, cardiac arrhythmias, rhabdomyolysis, and renal failure, green urine)",
    ],
    routes: [
      "Non elevated ICP/head trauma dosing 5-50mcg/kg/min (unless specified by sending physician)",
      "Elevated ICP: 60-100 mcg/kg/min may be needed. (MAX DOSE- 100mcg/kg/min in ICP patients only.)",
      "Titrate dose 5-10mcg/kg/min every 5-10 min until appropriate level of sedation is achieved.",
      "Bolus dosing of 0.5-1 mg/kg may be used to quickly sedate. Use caution in hypotensive patients and the elderly. ",
      "Continuous IV infusion or PRN bolus to maintain appropriate level of sedation and ventilator synchrony",
    ],
    ivInfusion: ["NA"],
  },
  {
    name: "VECURONIUM",
    tradeName: "Norcuron",
    action: "Non-depolarizing skeletal muscle relaxant.",
    indications: [
      "To provide paralysis (paralyzing dose) for rapid sequence intubation if succinylcholine is contraindicated.",
      " To maintain paralysis (maintenance dose) after intubation after adequate sedation is provided.",
      "To relieve isolated masseter muscle spasm due to succinylcholine.",
    ],
    contraindications: ["Known sensitivity to vecuronium."],
    sideEffects: [
      "Vecuronium causes paralysis, not analgesia or amnesia; patients must receive adequate sedation.  Patient will require airway management and ventilation. ",
    ],
    routes: [
      "Doses should be calculated based on ideal body weight (IBW).",
      "Paralyzing Dose: 0.15 mg/kg IV or IO.  Usual adult dose is 10 mg.  Administer only after paralysis due to succinylcholine has begun to wear off as evidenced by patient movement",
      "Maintenance Dose: 0.01-0.015 mg/kg IV or IO 25-40 minutes after initial paralysis, then every 12-15 minutes as needed or 1 mcg/kg/min IV or IO infusion. ",
    ],
    ivInfusion: ["NA"],
  },
];

export default dataList;
